/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deu.cse.team.booking;

import deu.cse.team.source.Api;
import deu.cse.team.source.BookingInfo;
import deu.cse.team.source.DefaultRoomRate;
import deu.cse.team.source.FileMgmt;
import java.io.IOException;
import java.io.StringReader;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;

/**
 *
 * @author CHANG
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Booking");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchAddressDlg = new javax.swing.JDialog();
        BookingSearchAddressField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        SearchAddressBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchAddressTable = new javax.swing.JTable();
        SearchAddressOkBtn = new javax.swing.JButton();
        SearchAddressCancelBtn = new javax.swing.JButton();
        ModifyBookingDlg = new javax.swing.JDialog();
        ModifyLoadBookingListBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ModifyBookingSearchIdxField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ModifyBookingTable = new javax.swing.JTable();
        ModifySearchIdxBtn = new javax.swing.JButton();
        ModifyCancelBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ModifyEntranceDateField = new javax.swing.JTextField();
        ModifyExitDateField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ModifyNameField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ModifyRoomNumField = new javax.swing.JTextField();
        ModifyMemberField = new javax.swing.JTextField();
        ModifyPhoneField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ModifyIdxLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ModifyAddressBtn = new javax.swing.JButton();
        ModifyAddressLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ModifyRateLabel = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ModifyBookingCancelBtn = new javax.swing.JButton();
        ModifyOKBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BookingEntranceDateCB1 = new javax.swing.JComboBox<>();
        BookingEntranceDateCB2 = new javax.swing.JComboBox<>();
        BookingEntranceDateCB3 = new javax.swing.JComboBox<>();
        BookingExitDateCB1 = new javax.swing.JComboBox<>();
        BookingExitDateCB2 = new javax.swing.JComboBox<>();
        BookingExitDateCB3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BookingMemberCB = new javax.swing.JComboBox<>();
        BookingNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BookingRoomNumField = new javax.swing.JTextField();
        BookingCheckChargeBtn = new javax.swing.JButton();
        BookingPhoneNumField1 = new javax.swing.JTextField();
        BookingPhoneNumField2 = new javax.swing.JTextField();
        BookingPhoneNumField3 = new javax.swing.JTextField();
        BookingRoomRateLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BookingSearchAddressBtn = new javax.swing.JButton();
        BookingModifyBtn = new javax.swing.JButton();
        BookingOkBtn = new javax.swing.JButton();
        BookingCancelBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AddressLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AddressLabel2 = new javax.swing.JLabel();
        AddressLabel3 = new javax.swing.JLabel();

        jLabel12.setText("도로명 주소 :");

        SearchAddressBtn.setText("검색");
        SearchAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchAddressBtnActionPerformed(evt);
            }
        });

        SearchAddressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "우편번호", "건물명", "도로명 주소"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SearchAddressTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(SearchAddressTable);

        SearchAddressOkBtn.setText("확인");
        SearchAddressOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchAddressOkBtnActionPerformed(evt);
            }
        });

        SearchAddressCancelBtn.setText("취소");
        SearchAddressCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchAddressCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchAddressDlgLayout = new javax.swing.GroupLayout(SearchAddressDlg.getContentPane());
        SearchAddressDlg.getContentPane().setLayout(SearchAddressDlgLayout);
        SearchAddressDlgLayout.setHorizontalGroup(
            SearchAddressDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchAddressDlgLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(SearchAddressDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SearchAddressDlgLayout.createSequentialGroup()
                        .addComponent(SearchAddressOkBtn)
                        .addGap(18, 18, 18)
                        .addComponent(SearchAddressCancelBtn))
                    .addGroup(SearchAddressDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(SearchAddressDlgLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BookingSearchAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchAddressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        SearchAddressDlgLayout.setVerticalGroup(
            SearchAddressDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchAddressDlgLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(SearchAddressDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingSearchAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(SearchAddressBtn))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchAddressDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchAddressOkBtn)
                    .addComponent(SearchAddressCancelBtn))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        ModifyLoadBookingListBtn.setText("불러오기");
        ModifyLoadBookingListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyLoadBookingListBtnActionPerformed(evt);
            }
        });

        jLabel13.setText("고유번호");

        jLabel14.setText("예약자 명단");

        ModifyBookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "고유번호", "이름", "입실날짜", "퇴실날짜", "호실", "인원", "연락처", "상태", "주소", "금액"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ModifyBookingTable);
        if (ModifyBookingTable.getColumnModel().getColumnCount() > 0) {
            ModifyBookingTable.getColumnModel().getColumn(0).setMinWidth(60);
            ModifyBookingTable.getColumnModel().getColumn(0).setMaxWidth(60);
            ModifyBookingTable.getColumnModel().getColumn(1).setMinWidth(60);
            ModifyBookingTable.getColumnModel().getColumn(1).setMaxWidth(60);
            ModifyBookingTable.getColumnModel().getColumn(4).setMinWidth(40);
            ModifyBookingTable.getColumnModel().getColumn(4).setMaxWidth(40);
            ModifyBookingTable.getColumnModel().getColumn(5).setMinWidth(40);
            ModifyBookingTable.getColumnModel().getColumn(5).setMaxWidth(40);
            ModifyBookingTable.getColumnModel().getColumn(7).setMinWidth(40);
            ModifyBookingTable.getColumnModel().getColumn(7).setMaxWidth(40);
            ModifyBookingTable.getColumnModel().getColumn(8).setMinWidth(0);
            ModifyBookingTable.getColumnModel().getColumn(8).setMaxWidth(0);
            ModifyBookingTable.getColumnModel().getColumn(9).setMinWidth(0);
            ModifyBookingTable.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        ModifySearchIdxBtn.setText("검색");
        ModifySearchIdxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifySearchIdxBtnActionPerformed(evt);
            }
        });

        ModifyCancelBtn.setText("취소");
        ModifyCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyCancelBtnActionPerformed(evt);
            }
        });

        jLabel15.setText("입실날짜:");

        jLabel16.setText("퇴실날짜:");

        ModifyExitDateField.setText("jTextField2");

        jLabel17.setText("이름:");

        ModifyNameField.setText("jTextField3");

        jLabel18.setText("호실:");

        jLabel19.setText("인원:");

        jLabel20.setText("연락처:");

        ModifyRoomNumField.setText("jTextField4");

        ModifyMemberField.setText("jTextField5");

        ModifyPhoneField.setText("jTextField6");

        jLabel21.setText("고유번호:");

        ModifyIdxLabel.setText("jLabel22");

        jLabel23.setText("주소:");

        ModifyAddressBtn.setText("주소변경");
        ModifyAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyAddressBtnActionPerformed(evt);
            }
        });

        ModifyAddressLabel.setText("jLabel24");

        jLabel25.setText("예상금액 :");

        ModifyRateLabel.setText("jLabel26");

        jLabel27.setText("원");

        jButton2.setText("예상금액 확인");

        ModifyBookingCancelBtn.setText("예약 취소");
        ModifyBookingCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyBookingCancelBtnActionPerformed(evt);
            }
        });

        ModifyOKBtn.setText("수정");
        ModifyOKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyOKBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModifyBookingDlgLayout = new javax.swing.GroupLayout(ModifyBookingDlg.getContentPane());
        ModifyBookingDlg.getContentPane().setLayout(ModifyBookingDlgLayout);
        ModifyBookingDlgLayout.setHorizontalGroup(
            ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyBookingDlgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifyBookingDlgLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(ModifyBookingSearchIdxField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModifySearchIdxBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(ModifyBookingDlgLayout.createSequentialGroup()
                        .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModifyBookingDlgLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifyBookingDlgLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifyBookingDlgLayout.createSequentialGroup()
                        .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addComponent(ModifyIdxLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ModifyRoomNumField)
                            .addComponent(ModifyMemberField)
                            .addComponent(ModifyPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(ModifyBookingDlgLayout.createSequentialGroup()
                        .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModifyBookingDlgLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(ModifyRateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(ModifyBookingDlgLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ModifyEntranceDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ModifyNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(ModifyExitDateField)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE))))
                    .addGroup(ModifyBookingDlgLayout.createSequentialGroup()
                        .addComponent(ModifyBookingCancelBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ModifyBookingDlgLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(ModifyAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ModifyAddressBtn)))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifyBookingDlgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifyBookingDlgLayout.createSequentialGroup()
                        .addComponent(ModifyOKBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModifyCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifyBookingDlgLayout.createSequentialGroup()
                        .addComponent(ModifyLoadBookingListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))))
        );
        ModifyBookingDlgLayout.setVerticalGroup(
            ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifyBookingDlgLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ModifyBookingSearchIdxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifySearchIdxBtn))
                .addGap(44, 44, 44)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModifyLoadBookingListBtn)
                .addGap(15, 15, 15)
                .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ModifyIdxLabel))
                .addGap(18, 18, 18)
                .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ModifyEntranceDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(ModifyRoomNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifyBookingDlgLayout.createSequentialGroup()
                        .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(ModifyExitDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(ModifyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ModifyBookingDlgLayout.createSequentialGroup()
                        .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(ModifyMemberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(ModifyPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyAddressBtn)
                    .addComponent(ModifyAddressLabel)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ModifyRateLabel)
                    .addComponent(jLabel27)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(ModifyBookingDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyCancelBtn)
                    .addComponent(ModifyBookingCancelBtn)
                    .addComponent(ModifyOKBtn))
                .addGap(22, 22, 22))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("입실 날짜");

        jLabel2.setText("퇴실 날짜");

        BookingEntranceDateCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        BookingEntranceDateCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        BookingEntranceDateCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        BookingExitDateCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        BookingExitDateCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        BookingExitDateCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel3.setText("고객 정보");

        jLabel4.setText("이름");

        jLabel5.setText("인원 수");

        BookingMemberCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        jLabel6.setText("호실");

        jLabel7.setText("전화번호");

        BookingCheckChargeBtn.setText("예상 금액 확인");
        BookingCheckChargeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingCheckChargeBtnActionPerformed(evt);
            }
        });

        BookingRoomRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BookingRoomRateLabel.setText("0");

        jLabel9.setText("주소 :");

        BookingSearchAddressBtn.setText("주소 검색");
        BookingSearchAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingSearchAddressBtnActionPerformed(evt);
            }
        });

        BookingModifyBtn.setText("예약 수정");
        BookingModifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingModifyBtnActionPerformed(evt);
            }
        });

        BookingOkBtn.setText("예약");
        BookingOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingOkBtnActionPerformed(evt);
            }
        });

        BookingCancelBtn.setText("이전");
        BookingCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingCancelBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("-");

        jLabel11.setText("-");

        jLabel8.setText("원");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(BookingEntranceDateCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BookingEntranceDateCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BookingEntranceDateCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(BookingExitDateCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BookingExitDateCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BookingExitDateCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(BookingMemberCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(BookingNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BookingPhoneNumField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BookingPhoneNumField2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(BookingRoomNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BookingPhoneNumField3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddressLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(AddressLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                    .addComponent(AddressLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BookingSearchAddressBtn))))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BookingRoomRateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(BookingCheckChargeBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(BookingModifyBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BookingOkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BookingCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(BookingEntranceDateCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookingEntranceDateCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookingEntranceDateCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BookingExitDateCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookingExitDateCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookingExitDateCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BookingNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(BookingRoomNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BookingMemberCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(BookingPhoneNumField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookingPhoneNumField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookingPhoneNumField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(AddressLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookingSearchAddressBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingCheckChargeBtn)
                    .addComponent(BookingRoomRateLabel)
                    .addComponent(jLabel8))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingModifyBtn)
                    .addComponent(BookingOkBtn)
                    .addComponent(BookingCancelBtn))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookingOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingOkBtnActionPerformed
        // TODO add your handling code here: 예약 버튼
        FileMgmt fileMgmt = new FileMgmt();
        String entranceDate = BookingEntranceDateCB1.getSelectedItem().toString() + "-"     // 입실 날짜
                + BookingEntranceDateCB2.getSelectedItem().toString() + "-"
                + BookingEntranceDateCB3.getSelectedItem().toString();
        String exitDate = BookingExitDateCB1.getSelectedItem().toString() + "-"             // 퇴실 날짜
                + BookingExitDateCB2.getSelectedItem().toString() + "-"
                + BookingExitDateCB3.getSelectedItem().toString();
        String customerName = BookingNameField.getText();                                   // 고객 이름
        String roomNumber = BookingRoomNumField.getText();                                   // 객실 번호
        String totalNum = BookingMemberCB.getSelectedItem().toString();                     // 인원수
        String phoneNum = BookingPhoneNumField1.getText() + "-"                             // 연락처
                + BookingPhoneNumField2.getText() + "-"
                + BookingPhoneNumField3.getText();
        String address = AddressLabel1.getText() + " "                                      // 주소
                + AddressLabel2.getText() + " "
                + AddressLabel3.getText();
        String roomRate = BookingRoomRateLabel.getText();                                   // 객실 요금
        String isCheckIn = "N";
        String str = entranceDate + "\t" + exitDate + "\t" + customerName + "\t" 
                + roomNumber + "\t" + totalNum + "\t" + phoneNum + "\t" 
                + address + "\t" + roomRate + "\t" + isCheckIn;
        try {
            fileMgmt.writeBookingFileData("C:\\DB\\BookingList.txt", str);
        } catch (IOException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, str);
    }//GEN-LAST:event_BookingOkBtnActionPerformed

    private void BookingCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingCancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BookingCancelBtnActionPerformed

    private void BookingSearchAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingSearchAddressBtnActionPerformed
        // TODO add your handling code here:
        SearchAddressDlg.setVisible(true);
        SearchAddressDlg.setLocationRelativeTo(this);
        SearchAddressDlg.setSize(550, 500);
    }//GEN-LAST:event_BookingSearchAddressBtnActionPerformed

    private void SearchAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchAddressBtnActionPerformed
        // TODO add your handling code here: 주소 검색 폼의 검색버튼(API 호출)
        Api api = new Api();
        DefaultTableModel model = (DefaultTableModel) SearchAddressTable.getModel();
        model.setRowCount(0);
        String xml = null;
        try {
            xml = api.Api(BookingSearchAddressField.getText());
            // XML 파싱
            InputSource is = new InputSource(new StringReader(xml));
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder documentBuilder;
            documentBuilder = factory.newDocumentBuilder();
            Document document = documentBuilder.parse(is);
            // root 구하기
            document.getDocumentElement().normalize();
            System.out.println("Root Element :" + document.getDocumentElement().getNodeName());
            NodeList nList = document.getElementsByTagName("item");

            String overlap = "";    // 중복 주소 확인
            String zipcode;         // 우편번호
            String bldnm;           // 건물명
            String road;            // 도로명주소
            
            for (int temp = 0; temp < nList.getLength(); temp++) {
                Node nNode = nList.item(temp);
                if (nNode.getNodeType() == Node.ELEMENT_NODE) {
                    Element eElement = (Element) nNode;
                    if (getTagValue("id", eElement).equals(overlap)) {
                        // 건물 동번호만 다른 중복된 주소이므로 다음으로 건너뜀
                        continue;
                    } else {
                        overlap = getTagValue("id", eElement);
                    }
                    zipcode = getTagValue("zipcode", eElement);
                    bldnm = getTagValue("bldnm", eElement);
                    road = getTagValue("road", eElement);
                    
                    // 테이블에 파싱된 데이터 삽입
                    model.addRow(new Object[]{zipcode, bldnm, road});
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchAddressBtnActionPerformed

    private void BookingCheckChargeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingCheckChargeBtnActionPerformed
        // TODO add your handling code here: 예상 금액 확인 버튼
        long lengthOfStay = 0;
        String entranceDate = BookingEntranceDateCB1.getSelectedItem().toString()             // 입실 날짜
                + BookingEntranceDateCB2.getSelectedItem().toString()
                + BookingEntranceDateCB3.getSelectedItem().toString();
        String exitDate = BookingExitDateCB1.getSelectedItem().toString()       // 퇴실 날짜
                + BookingExitDateCB2.getSelectedItem().toString()
                + BookingExitDateCB3.getSelectedItem().toString();
        SimpleDateFormat format = new SimpleDateFormat("yyyyMMdd");
        try {
            lengthOfStay = format.parse(exitDate).getTime() - format.parse(entranceDate).getTime();
        } catch (ParseException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
        lengthOfStay /= (24 * 60 * 60 * 1000);
        lengthOfStay = Math.abs(lengthOfStay);
        DefaultRoomRate defaultRoomRate = new DefaultRoomRate();
        BookingRoomRateLabel.setText(defaultRoomRate.DefaultRoomRate((int)lengthOfStay));
    }//GEN-LAST:event_BookingCheckChargeBtnActionPerformed

    private void SearchAddressOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchAddressOkBtnActionPerformed
        // TODO add your handling code here:
        int row = SearchAddressTable.getSelectedRow();
        TableModel addressData = SearchAddressTable.getModel();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "선택된 주소가 없습니다.");
        } else {
            if (ModifyBookingDlg.isVisible()) {
                ModifyAddressLabel.setText(String.format("%s %s %s", 
                        addressData.getValueAt(row, 0).toString(), 
                        addressData.getValueAt(row, 1).toString(), 
                        addressData.getValueAt(row, 2).toString()));
            } else {
                AddressLabel1.setText(addressData.getValueAt(row, 0).toString());
                AddressLabel2.setText(addressData.getValueAt(row, 1).toString());
                AddressLabel3.setText(addressData.getValueAt(row, 2).toString());
            }
            SearchAddressDlg.setVisible(false);
        }
    }//GEN-LAST:event_SearchAddressOkBtnActionPerformed

    private void SearchAddressCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchAddressCancelBtnActionPerformed
        // TODO add your handling code here:
        SearchAddressDlg.dispose();
    }//GEN-LAST:event_SearchAddressCancelBtnActionPerformed

    private void BookingModifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingModifyBtnActionPerformed
        // TODO add your handling code here:
        ModifyBookingDlg.setVisible(true);
        ModifyBookingDlg.setLocationRelativeTo(this);
        ModifyBookingDlg.setSize(550, 800);
        DefaultTableModel model = (DefaultTableModel) ModifyBookingTable.getModel();
        model.setRowCount(0);
        loadBookingData();
    }//GEN-LAST:event_BookingModifyBtnActionPerformed

    private void ModifySearchIdxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifySearchIdxBtnActionPerformed
        // TODO add your handling code here:
        String idx = ModifyBookingSearchIdxField.getText();
        if (!(idx.equals("") || (Integer.parseInt(idx) > ModifyBookingTable.getComponentCount()))) {
            for (int i = 0; i <= ModifyBookingTable.getComponentCount(); i++) {
                if (idx.equals(ModifyBookingTable.getValueAt(i, 0))) {
                    ModifyBookingTable.requestFocus();
                    ModifyBookingTable.changeSelection(i, 0, false, false);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "유효한 고유번호를 입력하세요.");
        }
    }//GEN-LAST:event_ModifySearchIdxBtnActionPerformed

    private void ModifyLoadBookingListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyLoadBookingListBtnActionPerformed
        // TODO add your handling code here:
        TableModel bookingData = ModifyBookingTable.getModel();
        int row = ModifyBookingTable.getSelectedRow();
        ModifyIdxLabel.setText(bookingData.getValueAt(row, 0).toString());
        ModifyNameField.setText(bookingData.getValueAt(row, 1).toString());
        ModifyEntranceDateField.setText(bookingData.getValueAt(row, 2).toString());
        ModifyExitDateField.setText(bookingData.getValueAt(row, 3).toString());
        ModifyRoomNumField.setText(bookingData.getValueAt(row, 4).toString());
        ModifyMemberField.setText(bookingData.getValueAt(row, 5).toString());
        ModifyPhoneField.setText(bookingData.getValueAt(row, 6).toString());
        ModifyAddressLabel.setText(bookingData.getValueAt(row, 8).toString());
        ModifyRateLabel.setText(bookingData.getValueAt(row, 9).toString());
    }//GEN-LAST:event_ModifyLoadBookingListBtnActionPerformed

    private void ModifyCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyCancelBtnActionPerformed
        // TODO add your handling code here:
        ModifyBookingDlg.dispose();
    }//GEN-LAST:event_ModifyCancelBtnActionPerformed

    private void ModifyBookingCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyBookingCancelBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ModifyBookingTable.getModel();
        model.removeRow(ModifyBookingTable.getSelectedRow());
    }//GEN-LAST:event_ModifyBookingCancelBtnActionPerformed

    private void ModifyOKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyOKBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ModifyOKBtnActionPerformed

    private void ModifyAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyAddressBtnActionPerformed
        // TODO add your handling code here:
        SearchAddressDlg.setVisible(true);
        SearchAddressDlg.setLocationRelativeTo(this);
        SearchAddressDlg.setSize(550, 500);
    }//GEN-LAST:event_ModifyAddressBtnActionPerformed
    // 입력한 tag 정보
    String getTagValue(String tag, Element eElement) {
        NodeList nlList = eElement.getElementsByTagName(tag).item(0).getChildNodes();
        Node nValue = (Node) nlList.item(0);
        if (nValue == null)
            return null;
        return nValue.getNodeValue();
    }
    
    private void loadBookingData() {
        ArrayList<BookingInfo> bookingInfo = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) ModifyBookingTable.getModel();
        try {
            FileMgmt fileMgmt = new FileMgmt();
            fileMgmt.readBookingFileData("C:\\DB\\BookingList.txt");
            fileMgmt.splitBookingFileData();
            bookingInfo = fileMgmt.returnBookingInfo();
            
            for (int i = 0; i < bookingInfo.size(); i++) {
                model.addRow(new Object[]{
                    bookingInfo.get(i).getIndex(),
                    bookingInfo.get(i).getName(),
                    bookingInfo.get(i).getEntrance(),
                    bookingInfo.get(i).getExit(),
                    bookingInfo.get(i).getRoom(),
                    bookingInfo.get(i).getPersonnel(),
                    bookingInfo.get(i).getPhonenumber(),
                    bookingInfo.get(i).getStatus(),
                    bookingInfo.get(i).getAddress(),
                    bookingInfo.get(i).getMoney()
                });
            }
        } catch (IOException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel1;
    private javax.swing.JLabel AddressLabel2;
    private javax.swing.JLabel AddressLabel3;
    private javax.swing.JButton BookingCancelBtn;
    private javax.swing.JButton BookingCheckChargeBtn;
    private javax.swing.JComboBox<String> BookingEntranceDateCB1;
    private javax.swing.JComboBox<String> BookingEntranceDateCB2;
    private javax.swing.JComboBox<String> BookingEntranceDateCB3;
    private javax.swing.JComboBox<String> BookingExitDateCB1;
    private javax.swing.JComboBox<String> BookingExitDateCB2;
    private javax.swing.JComboBox<String> BookingExitDateCB3;
    private javax.swing.JComboBox<String> BookingMemberCB;
    private javax.swing.JButton BookingModifyBtn;
    private javax.swing.JTextField BookingNameField;
    private javax.swing.JButton BookingOkBtn;
    private javax.swing.JTextField BookingPhoneNumField1;
    private javax.swing.JTextField BookingPhoneNumField2;
    private javax.swing.JTextField BookingPhoneNumField3;
    private javax.swing.JTextField BookingRoomNumField;
    private javax.swing.JLabel BookingRoomRateLabel;
    private javax.swing.JButton BookingSearchAddressBtn;
    private javax.swing.JTextField BookingSearchAddressField;
    private javax.swing.JButton ModifyAddressBtn;
    private javax.swing.JLabel ModifyAddressLabel;
    private javax.swing.JButton ModifyBookingCancelBtn;
    private javax.swing.JDialog ModifyBookingDlg;
    private javax.swing.JTextField ModifyBookingSearchIdxField;
    private javax.swing.JTable ModifyBookingTable;
    private javax.swing.JButton ModifyCancelBtn;
    private javax.swing.JTextField ModifyEntranceDateField;
    private javax.swing.JTextField ModifyExitDateField;
    private javax.swing.JLabel ModifyIdxLabel;
    private javax.swing.JButton ModifyLoadBookingListBtn;
    private javax.swing.JTextField ModifyMemberField;
    private javax.swing.JTextField ModifyNameField;
    private javax.swing.JButton ModifyOKBtn;
    private javax.swing.JTextField ModifyPhoneField;
    private javax.swing.JLabel ModifyRateLabel;
    private javax.swing.JTextField ModifyRoomNumField;
    private javax.swing.JButton ModifySearchIdxBtn;
    private javax.swing.JButton SearchAddressBtn;
    private javax.swing.JButton SearchAddressCancelBtn;
    private javax.swing.JDialog SearchAddressDlg;
    private javax.swing.JButton SearchAddressOkBtn;
    private javax.swing.JTable SearchAddressTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
