/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deu.cse.team.checkout;

import deu.cse.team.source.BookingInfo;
import deu.cse.team.source.CurrentTime;
import deu.cse.team.source.DefaultRoomRate;
import deu.cse.team.source.FileMgmt;
import deu.cse.team.source.InitRoomComboBox;
import deu.cse.team.source.ServiceOrderListInfo;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author LGuser
 */
public class CheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CheckOut
     */
    public CheckOut() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Check-Out");
        DefaultComboBoxModel model = (DefaultComboBoxModel) CheckOutRoomCB.getModel();
        model.addElement("선택");
        new InitRoomComboBox(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentTypeDlg = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        PaymentCashRB = new javax.swing.JRadioButton();
        PaymentCreditRB = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CreditCardNumField1 = new javax.swing.JTextField();
        CreditCardNumField2 = new javax.swing.JTextField();
        CreditCardNumField3 = new javax.swing.JTextField();
        CreditCardNumField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CreditValidMonthField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        CreditValidYearField = new javax.swing.JTextField();
        CreditCVCField = new javax.swing.JTextField();
        PaymentTypeOkBtn = new javax.swing.JButton();
        PaymentTypeCancelBtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CheckOutRoomCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CheckOutEnterField = new javax.swing.JTextField();
        CheckOutExitField = new javax.swing.JTextField();
        CheckOutExtraDateField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CheckOutServicePriceField = new javax.swing.JTextField();
        CheckOutExtraPriceField = new javax.swing.JTextField();
        CheckOutOkBtn = new javax.swing.JButton();
        CheckOutCancelBtn = new javax.swing.JButton();
        CheckOutSearchBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CheckOutRoomPriceField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CheckOutTotalPriceField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CheckOutCurrentDateField = new javax.swing.JTextField();
        PaymentTypeBtn = new javax.swing.JButton();
        PaymentTypeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IndexLabel = new javax.swing.JLabel();

        jLabel11.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel11.setText("결제 수단 선택");

        buttonGroup1.add(PaymentCashRB);
        PaymentCashRB.setSelected(true);
        PaymentCashRB.setText("현금");
        PaymentCashRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentCashRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(PaymentCreditRB);
        PaymentCreditRB.setText("신용카드");
        PaymentCreditRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentCreditRBActionPerformed(evt);
            }
        });

        jLabel12.setText("카드번호 :");

        jLabel13.setText("유효기간 :");

        jLabel14.setText("CVC :");

        CreditCardNumField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CreditCardNumField1.setEnabled(false);

        CreditCardNumField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CreditCardNumField2.setEnabled(false);

        CreditCardNumField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CreditCardNumField3.setEnabled(false);

        CreditCardNumField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CreditCardNumField4.setEnabled(false);

        jLabel15.setText("-");

        jLabel16.setText("-");

        jLabel17.setText("-");

        CreditValidMonthField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CreditValidMonthField.setEnabled(false);

        jLabel18.setText("/");

        CreditValidYearField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CreditValidYearField.setEnabled(false);

        CreditCVCField.setEnabled(false);

        PaymentTypeOkBtn.setText("등록");
        PaymentTypeOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentTypeOkBtnActionPerformed(evt);
            }
        });

        PaymentTypeCancelBtn.setText("취소");
        PaymentTypeCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentTypeCancelBtnActionPerformed(evt);
            }
        });

        jLabel19.setText("(MM/YYYY)");

        javax.swing.GroupLayout PaymentTypeDlgLayout = new javax.swing.GroupLayout(PaymentTypeDlg.getContentPane());
        PaymentTypeDlg.getContentPane().setLayout(PaymentTypeDlgLayout);
        PaymentTypeDlgLayout.setHorizontalGroup(
            PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentTypeDlgLayout.createSequentialGroup()
                .addGroup(PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentTypeDlgLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PaymentTypeDlgLayout.createSequentialGroup()
                                .addGroup(PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PaymentTypeDlgLayout.createSequentialGroup()
                                        .addComponent(CreditValidMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CreditValidYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19))
                                    .addComponent(CreditCVCField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PaymentCreditRB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PaymentCashRB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PaymentTypeDlgLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CreditCardNumField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(PaymentTypeDlgLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CreditCardNumField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CreditCardNumField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CreditCardNumField4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(PaymentTypeDlgLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(PaymentTypeOkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PaymentTypeCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        PaymentTypeDlgLayout.setVerticalGroup(
            PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentTypeDlgLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel11)
                .addGap(29, 29, 29)
                .addComponent(PaymentCashRB)
                .addGap(18, 18, 18)
                .addComponent(PaymentCreditRB)
                .addGap(29, 29, 29)
                .addGroup(PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CreditCardNumField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(CreditCardNumField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(CreditCardNumField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(CreditCardNumField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CreditValidMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(CreditValidYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addGap(18, 18, 18)
                .addGroup(PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CreditCVCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(PaymentTypeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentTypeOkBtn)
                    .addComponent(PaymentTypeCancelBtn))
                .addGap(26, 26, 26))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("호실");

        jLabel3.setText("입실일자");

        CheckOutRoomCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutRoomCBActionPerformed(evt);
            }
        });

        jLabel4.setText("퇴실일자");

        jLabel5.setText("추가일자");

        CheckOutEnterField.setEditable(false);
        CheckOutEnterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutEnterFieldActionPerformed(evt);
            }
        });

        CheckOutExitField.setEditable(false);

        CheckOutExtraDateField.setEditable(false);

        jLabel6.setText("서비스 이용 금액");

        jLabel7.setText("추가 금액");

        CheckOutServicePriceField.setEditable(false);

        CheckOutExtraPriceField.setEditable(false);

        CheckOutOkBtn.setText("체크아웃");
        CheckOutOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutOkBtnActionPerformed(evt);
            }
        });

        CheckOutCancelBtn.setText("이전");
        CheckOutCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutCancelBtnActionPerformed(evt);
            }
        });

        CheckOutSearchBtn.setText("검색");
        CheckOutSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutSearchBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("객실 금액");

        CheckOutRoomPriceField.setEditable(false);

        jLabel9.setText("총 금액");

        CheckOutTotalPriceField.setEditable(false);

        jLabel10.setText("현재날짜");

        CheckOutCurrentDateField.setEditable(false);

        PaymentTypeBtn.setText("결제 수단");
        PaymentTypeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentTypeBtnActionPerformed(evt);
            }
        });

        PaymentTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("고유번호 :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(CheckOutOkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CheckOutCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IndexLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckOutCurrentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CheckOutServicePriceField)
                                        .addComponent(CheckOutRoomPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(CheckOutTotalPriceField)
                                        .addComponent(CheckOutExtraPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CheckOutExtraDateField))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CheckOutEnterField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CheckOutExitField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(PaymentTypeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PaymentTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                        .addGap(38, 38, 38)))))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckOutRoomCB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckOutSearchBtn)
                        .addGap(24, 273, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CheckOutRoomCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckOutSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IndexLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CheckOutRoomPriceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(CheckOutCurrentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CheckOutEnterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(CheckOutExitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CheckOutExtraDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CheckOutServicePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaymentTypeBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CheckOutExtraPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaymentTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CheckOutTotalPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckOutOkBtn)
                    .addComponent(CheckOutCancelBtn))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckOutRoomCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutRoomCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckOutRoomCBActionPerformed

    private void CheckOutEnterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutEnterFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CheckOutEnterFieldActionPerformed

    private void CheckOutSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutSearchBtnActionPerformed
        // TODO add your handling code here:
        String str = CheckOutRoomCB.getSelectedItem().toString();
        if (!str.equals("선택")) {
            returnGueseData(); //객실/서비스 이용 금액
            currentDate(); //현재 날짜, 추가금액
            int totalPrice = Integer.parseInt(CheckOutRoomPriceField.getText())
                    + Integer.parseInt(CheckOutServicePriceField.getText())
                    + Integer.parseInt(CheckOutExtraPriceField.getText());
            CheckOutTotalPriceField.setText(Integer.toString(totalPrice));
        } else {
            JOptionPane.showMessageDialog(null, "호실을 선택해주세요.");
        }
    }//GEN-LAST:event_CheckOutSearchBtnActionPerformed

    private void CheckOutOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutOkBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<BookingInfo> bookingInfo = new ArrayList<>();
        String selectedRoom = CheckOutRoomCB.getSelectedItem().toString();
        FileMgmt fileMgmt = new FileMgmt();
        fileMgmt.readBookingFileData("C:\\DB\\BookingList.txt");
        fileMgmt.splitBookingFileData();
        String revenue = String.format("%s\t%s~%s\t%s\t%s\t%s\t%s", 
                IndexLabel.getText(),
                CheckOutEnterField.getText(),
                CheckOutExitField.getText(),
                CheckOutExtraDateField.getText(),
                CheckOutRoomPriceField.getText(),
                CheckOutServicePriceField.getText(),
                CheckOutExtraPriceField.getText());
        try (PrintWriter pw = new PrintWriter("C:\\DB\\BookingList.txt")) {
            bookingInfo = fileMgmt.returnBookingInfo();
            for (int i = 0; i < bookingInfo.size(); i++) {
                if (bookingInfo.get(i).getRoom().equals(selectedRoom)) {
                    bookingInfo.get(i).setStatus("E");

                }
                String data = String.format("%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s",
                        bookingInfo.get(i).getIndex(), bookingInfo.get(i).getEntrance(),
                        bookingInfo.get(i).getExit(), bookingInfo.get(i).getName(),
                        bookingInfo.get(i).getRoom(), bookingInfo.get(i).getPersonnel(),
                        bookingInfo.get(i).getPhonenumber(), bookingInfo.get(i).getAddress(),
                        bookingInfo.get(i).getMoney(), bookingInfo.get(i).getStatus());
                pw.println(data);
            }
            fileMgmt.writeRevenueFileData("C:\\DB\\RevenueList.txt", revenue);
            JOptionPane.showMessageDialog(null, "체크아웃 완료");
        } catch (IOException ex) {
            Logger.getLogger(CheckOut.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "체크아웃 실패");
        }
    }//GEN-LAST:event_CheckOutOkBtnActionPerformed

    private void CheckOutCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutCancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CheckOutCancelBtnActionPerformed

    private void PaymentTypeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentTypeBtnActionPerformed
        // TODO add your handling code here:
        PaymentTypeDlg.setVisible(true);
        PaymentTypeDlg.setLocationRelativeTo(this);
        PaymentTypeDlg.setSize(450, 450);
    }//GEN-LAST:event_PaymentTypeBtnActionPerformed

    private void PaymentCashRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentCashRBActionPerformed
        // TODO add your handling code here:
        CreditCardNumField1.setEnabled(false);
        CreditCardNumField2.setEnabled(false);
        CreditCardNumField3.setEnabled(false);
        CreditCardNumField4.setEnabled(false);
        CreditValidMonthField.setEnabled(false);
        CreditValidYearField.setEnabled(false);
        CreditCVCField.setEnabled(false);
    }//GEN-LAST:event_PaymentCashRBActionPerformed

    private void PaymentCreditRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentCreditRBActionPerformed
        // TODO add your handling code here:
        CreditCardNumField1.setEnabled(true);
        CreditCardNumField2.setEnabled(true);
        CreditCardNumField3.setEnabled(true);
        CreditCardNumField4.setEnabled(true);
        CreditValidMonthField.setEnabled(true);
        CreditValidYearField.setEnabled(true);
        CreditCVCField.setEnabled(true);
    }//GEN-LAST:event_PaymentCreditRBActionPerformed

    private void PaymentTypeOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentTypeOkBtnActionPerformed
        // TODO add your handling code here:
        if (PaymentCreditRB.isSelected()) {
            PaymentTypeLabel.setText("신용카드");
        } else {
            PaymentTypeLabel.setText("현금");
        }
        JOptionPane.showMessageDialog(null, "등록 완료");
        PaymentTypeDlg.dispose();
    }//GEN-LAST:event_PaymentTypeOkBtnActionPerformed

    private void PaymentTypeCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentTypeCancelBtnActionPerformed
        // TODO add your handling code here:
        PaymentTypeDlg.dispose();
    }//GEN-LAST:event_PaymentTypeCancelBtnActionPerformed

    private void returnGueseData() { //객실, 서비스 금액
        ArrayList<BookingInfo> bookingInfo = new ArrayList<>();
        ArrayList<ServiceOrderListInfo> serviceOrderListInfo = new ArrayList<>();
        String room = CheckOutRoomCB.getSelectedItem().toString();
        int money = 0;
        String[] productPrice;
        try {
            FileMgmt fileMgmt = new FileMgmt();
            fileMgmt.readBookingFileData("C:\\DB\\BookingList.txt");
            fileMgmt.readServiceOrderListFileData("C:\\DB\\ServiceOrderList.txt");
            fileMgmt.splitBookingFileData();
            fileMgmt.splitServiceOrderListFileData();
            bookingInfo = fileMgmt.returnBookingInfo();
            serviceOrderListInfo = fileMgmt.returnServiceOrderListInfo();
            for (int i = 0; i < bookingInfo.size(); i++) {
                if (bookingInfo.get(i).getRoom().equals(room)) {
                    IndexLabel.setText(bookingInfo.get(i).getIndex());
                    CheckOutEnterField.setText(bookingInfo.get(i).getEntrance());
                    CheckOutExitField.setText(bookingInfo.get(i).getExit());
                    CheckOutRoomPriceField.setText(bookingInfo.get(i).getMoney());
                    productPrice = serviceOrderListInfo.get(i).getMoney().split("/");
                    for (int j = 0; j < productPrice.length; j++) {
                        money += Integer.parseInt(productPrice[j]);
                    }
                }
            }
        } catch (IOException e) {
        }
        CheckOutServicePriceField.setText(Integer.toString(money));
    }

    private void currentDate() { //현재 날짜, 추가금액
        long diffDays = 0;
        SimpleDateFormat format;
        String currentDate = new CurrentTime().getCurrentDate();
        String exitDate = CheckOutExitField.getText();

        try {
            format = new SimpleDateFormat("yyyy-MM-dd");
            diffDays = format.parse(currentDate).getTime() - format.parse(exitDate).getTime();
        } catch (ParseException ex) {
            Logger.getLogger(CheckOut.class.getName()).log(Level.SEVERE, null, ex);
        }
        CheckOutCurrentDateField.setText(currentDate);

        diffDays /= (24 * 60 * 60 * 1000);
        CheckOutExtraDateField.setText(Long.toString(diffDays));
        //추가금액
        CheckOutExtraPriceField.setText(new DefaultRoomRate().DefaultRoomRate((int) diffDays));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckOutCancelBtn;
    private javax.swing.JTextField CheckOutCurrentDateField;
    private javax.swing.JTextField CheckOutEnterField;
    private javax.swing.JTextField CheckOutExitField;
    private javax.swing.JTextField CheckOutExtraDateField;
    private javax.swing.JTextField CheckOutExtraPriceField;
    private javax.swing.JButton CheckOutOkBtn;
    private javax.swing.JComboBox<String> CheckOutRoomCB;
    private javax.swing.JTextField CheckOutRoomPriceField;
    private javax.swing.JButton CheckOutSearchBtn;
    private javax.swing.JTextField CheckOutServicePriceField;
    private javax.swing.JTextField CheckOutTotalPriceField;
    private javax.swing.JTextField CreditCVCField;
    private javax.swing.JTextField CreditCardNumField1;
    private javax.swing.JTextField CreditCardNumField2;
    private javax.swing.JTextField CreditCardNumField3;
    private javax.swing.JTextField CreditCardNumField4;
    private javax.swing.JTextField CreditValidMonthField;
    private javax.swing.JTextField CreditValidYearField;
    private javax.swing.JLabel IndexLabel;
    private javax.swing.JRadioButton PaymentCashRB;
    private javax.swing.JRadioButton PaymentCreditRB;
    private javax.swing.JButton PaymentTypeBtn;
    private javax.swing.JButton PaymentTypeCancelBtn;
    private javax.swing.JDialog PaymentTypeDlg;
    private javax.swing.JLabel PaymentTypeLabel;
    private javax.swing.JButton PaymentTypeOkBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
