/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deu.cse.team.management;

import deu.cse.team.source.LoadRoomData;
import deu.cse.team.source.ModifyRoomData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KYG
 */
public class MgmtRoomRate extends javax.swing.JFrame {

    /**
     * Creates new form MgmtRoomRate
     */
    public MgmtRoomRate() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Manage Room");
        new LoadRoomData((DefaultTableModel) MgmtRoomRateTable.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModifyRoomDlg = new javax.swing.JDialog();
        ModifyRoomNumLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ModifyRoomDataOkBtn = new javax.swing.JButton();
        ModifyRoomDataCancelBtn = new javax.swing.JButton();
        RoomStatusYRB = new javax.swing.JRadioButton();
        RoomStatusNRB = new javax.swing.JRadioButton();
        ModifyRoomRateField = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        MgmtRateRoomNumField = new javax.swing.JTextField();
        MgmtRateSearchRoomBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MgmtRoomRateTable = new javax.swing.JTable();
        MgmtRoomCancelBtn = new javax.swing.JButton();
        ModifyRoomBtn = new javax.swing.JButton();

        ModifyRoomNumLabel.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        ModifyRoomNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ModifyRoomNumLabel.setToolTipText("");
        ModifyRoomNumLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel4.setText("호실 수정");

        jLabel3.setText("요금 :");

        jLabel5.setText("가용 여부 :");

        ModifyRoomDataOkBtn.setText("완료");
        ModifyRoomDataOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyRoomDataOkBtnActionPerformed(evt);
            }
        });

        ModifyRoomDataCancelBtn.setText("취소");
        ModifyRoomDataCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyRoomDataCancelBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(RoomStatusYRB);
        RoomStatusYRB.setText("Y");

        buttonGroup1.add(RoomStatusNRB);
        RoomStatusNRB.setText("N");

        javax.swing.GroupLayout ModifyRoomDlgLayout = new javax.swing.GroupLayout(ModifyRoomDlg.getContentPane());
        ModifyRoomDlg.getContentPane().setLayout(ModifyRoomDlgLayout);
        ModifyRoomDlgLayout.setHorizontalGroup(
            ModifyRoomDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyRoomDlgLayout.createSequentialGroup()
                .addGroup(ModifyRoomDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifyRoomDlgLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(ModifyRoomDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ModifyRoomDlgLayout.createSequentialGroup()
                                .addComponent(ModifyRoomNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(ModifyRoomDlgLayout.createSequentialGroup()
                                .addGroup(ModifyRoomDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(ModifyRoomDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RoomStatusNRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RoomStatusYRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ModifyRoomRateField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))))
                    .addGroup(ModifyRoomDlgLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(ModifyRoomDataOkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModifyRoomDataCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        ModifyRoomDlgLayout.setVerticalGroup(
            ModifyRoomDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyRoomDlgLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(ModifyRoomDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifyRoomNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(ModifyRoomDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ModifyRoomRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ModifyRoomDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RoomStatusYRB))
                .addGap(18, 18, 18)
                .addComponent(RoomStatusNRB)
                .addGap(56, 56, 56)
                .addGroup(ModifyRoomDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyRoomDataOkBtn)
                    .addComponent(ModifyRoomDataCancelBtn))
                .addGap(24, 24, 24))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("호실");

        MgmtRateSearchRoomBtn.setText("검색");
        MgmtRateSearchRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MgmtRateSearchRoomBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        jLabel2.setText("객실 요금 관리");

        MgmtRoomRateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "호실", "요금", "가용여부"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MgmtRoomRateTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(MgmtRoomRateTable);

        MgmtRoomCancelBtn.setText("이전");
        MgmtRoomCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MgmtRoomCancelBtnActionPerformed(evt);
            }
        });

        ModifyRoomBtn.setText("수정");
        ModifyRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyRoomBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ModifyRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MgmtRoomCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(MgmtRateRoomNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(MgmtRateSearchRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel2))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MgmtRateRoomNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MgmtRateSearchRoomBtn))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyRoomBtn)
                    .addComponent(MgmtRoomCancelBtn))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MgmtRateSearchRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MgmtRateSearchRoomBtnActionPerformed
        // TODO add your handling code here:
        String str = MgmtRateRoomNumField.getText();
        for (int i = 0; i < MgmtRoomRateTable.getRowCount(); i++) {
            if (str.equals(MgmtRoomRateTable.getValueAt(i, 0))) {
                MgmtRoomRateTable.requestFocus();
                MgmtRoomRateTable.changeSelection(i, 0, false, false);
            }
        }
    }//GEN-LAST:event_MgmtRateSearchRoomBtnActionPerformed

    private void ModifyRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyRoomBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) MgmtRoomRateTable.getModel();
        int row = MgmtRoomRateTable.getSelectedRow();
        try {
            ModifyRoomNumLabel.setText(model.getValueAt(row, 0).toString());
            ModifyRoomRateField.setText(model.getValueAt(row, 1).toString());
            if (model.getValueAt(row, 2).toString().equals("Y"))
                RoomStatusYRB.setSelected(true);
            else
                RoomStatusNRB.setSelected(true);
            ModifyRoomDlg.setVisible(true);
            ModifyRoomDlg.setLocationRelativeTo(this);
            ModifyRoomDlg.setSize(400, 400);
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "선택된 항목이 없습니다.");
        }
    }//GEN-LAST:event_ModifyRoomBtnActionPerformed

    private void MgmtRoomCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MgmtRoomCancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_MgmtRoomCancelBtnActionPerformed

    private void ModifyRoomDataOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyRoomDataOkBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) MgmtRoomRateTable.getModel();
        int index = Integer.parseInt(ModifyRoomNumLabel.getText());
        String status;
        if (RoomStatusYRB.isSelected())
            status = "Y";
        else
            status = "N";
            
        model.removeRow(index);
        model.insertRow(index, new Object[] {
            ModifyRoomNumLabel.getText(),
            ModifyRoomRateField.getText(),
            status
        });
        try {
            new ModifyRoomData(model);
            JOptionPane.showMessageDialog(null, "수정 완료");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "오류 발생!");
        }
        ModifyRoomDlg.dispose();
    }//GEN-LAST:event_ModifyRoomDataOkBtnActionPerformed

    private void ModifyRoomDataCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyRoomDataCancelBtnActionPerformed
        // TODO add your handling code here:
        ModifyRoomDlg.dispose();
    }//GEN-LAST:event_ModifyRoomDataCancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MgmtRoomRate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MgmtRoomRate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MgmtRoomRate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MgmtRoomRate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MgmtRoomRate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MgmtRateRoomNumField;
    private javax.swing.JButton MgmtRateSearchRoomBtn;
    private javax.swing.JButton MgmtRoomCancelBtn;
    private javax.swing.JTable MgmtRoomRateTable;
    private javax.swing.JButton ModifyRoomBtn;
    private javax.swing.JButton ModifyRoomDataCancelBtn;
    private javax.swing.JButton ModifyRoomDataOkBtn;
    private javax.swing.JDialog ModifyRoomDlg;
    private javax.swing.JLabel ModifyRoomNumLabel;
    private javax.swing.JTextField ModifyRoomRateField;
    private javax.swing.JRadioButton RoomStatusNRB;
    private javax.swing.JRadioButton RoomStatusYRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
